language:        generic
sudo:            required
services:
  - docker

before_install:
  #get build context from client directory
  - docker build -t djxc65/react-test -f ./client/Dockerfile.dev ./client

script:
  #ensure npm will close by adding coverage flag
  - docker run -e CI=true djxc65/react-test npm test

after_success:
  - docker build -t djxc65/multi-client ./client
  - docker build -t djxc65/multi-nginx ./nginx
  - docker build -t djxc65/multi-server ./server
  - docker build -t djxc65/multi-worker ./worker
  #login to docker CLI using env variable in Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push djxc65/multi-client
  - docker push djxc65/multi-nginx
  - docker push djxc65/multi-server
  - docker push djxc65/multi-worker

deploy:
  #config to tell travis how to deploy to AWS
  #travis is delivered with some presupported platforms
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-789779327928"
  bucket_path: "docker-multi"
  on:
    #only deploy if changes are merged into master branch.
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
