sudo: required
services:
  - docker


before_install:
  #get build context from client directory
  - docker build -t dcamp01/react-test -f ./client/Dockerfile.dev ./client

script:
  #ensure npm will close by adding coverage flag
  - docker run dcamp01/react-test npm test -- --coverage

after_success:
  - docker build -t dcamp01/multi-client ./client
  - docker build -t dcamp01/multi-nginx ./nginx
  - docker build -t dcamp01/multi-server ./server
  - docker build -t dcamp01/multi-worker ./worker
#login to docker CLI using env variable in Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub
- docker push dcamp01/multi-client
- docker push dcamp01/multi-nginx
- docker push dcamp01/multi-server
- docker push dcamp01/multi-worker
